<a href="https://colab.research.google.com/github/Jadrianp29/testreko/blob/main/JesusAdrianAguilarPerezRetoEmpleados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Importar librerias necesarias

In [1]:
import pandas as pd
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
import numpy as np


2.Leer el archivo

In [2]:
EmpleadosAttrition=pd.read_csv('EmpleadosAttrition.csv',)
EmpleadosAttrition.columns


Index(['Age', 'BusinessTravel', 'Department', 'DistanceFromHome', 'Education',
       'EducationField', 'EmployeeCount', 'EmployeeNumber',
       'EnvironmentSatisfaction', 'Gender', 'JobInvolvement', 'JobLevel',
       'JobRole', 'JobSatisfaction', 'MaritalStatus', 'MonthlyIncome',
       'NumCompaniesWorked', 'HiringDate', 'Over18', 'OverTime',
       'PercentSalaryHike', 'PerformanceRating', 'RelationshipSatisfaction',
       'StandardHours', 'TotalWorkingYears', 'TrainingTimesLastYear',
       'WorkLifeBalance', 'YearsInCurrentRole', 'YearsSinceLastPromotion',
       'Attrition'],
      dtype='object')

3.	Elimina las columnas que, con alta probabilidad, no tienen relación alguna con la salida.

In [3]:
EmpleadosAttrition.drop(['EmployeeCount', 'EmployeeNumber', 'Over18', 'StandardHours'], axis=1, inplace=True)

a.	Crea una columna llamada Year y obtén el año de contratación del empleado a partir de su fecha ‘HiringDate’.
b.	Crea una columna llamada YearsAtCompany que contenga los años que el empleado lleva en la compañía hasta el año 2018. Para su cálculo, usa la variable Year que acabas de crear.


In [4]:
EmpleadosAttrition.loc[229, 'HiringDate']

'2/30/2012'

In [5]:
EmpleadosAttrition['HiringDate'] = pd.to_datetime(EmpleadosAttrition['HiringDate'],errors='coerce')
EmpleadosAttrition['Year'] = EmpleadosAttrition['HiringDate'].dt.year
EmpleadosAttrition['YearsAtCompany'] = 2018 - EmpleadosAttrition['Year']


In [6]:
EmpleadosAttrition['YearsAtCompany']

0       5.0
1       3.0
2       1.0
3       8.0
4       7.0
       ... 
395     5.0
396     2.0
397    10.0
398     0.0
399     8.0
Name: YearsAtCompany, Length: 400, dtype: float64

5.	La DistanceFromHome está dada en kilómetros, pero tiene las letras “km” al final y así no puede ser entera:
a.	Renombra la variable DistanceFromHome a DistanceFromHome_km.
b.	Crea una nueva variable DistanceFromHome que sea entera, es decir, solo con números.


In [7]:
EmpleadosAttrition.rename(columns={'DistanceFromHome':'DistanceFromHome_km'}, inplace=True)
EmpleadosAttrition['DistanceFromHome']=EmpleadosAttrition['DistanceFromHome_km'].str.replace('km','').astype(int)
EmpleadosAttrition['DistanceFromHome']

0       1
1       6
2       7
3       7
4      15
       ..
395    14
396    20
397    11
398     4
399    14
Name: DistanceFromHome, Length: 400, dtype: int64

6.	Borra las columnas Year, HiringDate y DistanceFromHome_km debido a que ya no son útiles.



In [8]:
EmpleadosAttrition.drop(['Year','HiringDate','DistanceFromHome_km'], axis=1, inplace=True)

7.	Aprovechando los ajustes que se están haciendo, la empresa desea saber si todos los departamentos tienen un ingreso promedio similar. Genera una nuevo frame llamado SueldoPromedioDepto que contenga el MonthlyIncome promedio por departamento de los empleados y colócalo en una variable llamada SueldoPromedio.

In [9]:
SueldoPromedioDepto = EmpleadosAttrition['MonthlyIncome'].groupby(EmpleadosAttrition['Department']).mean()


8.	La variable MonthlyIncome tiene un valor numérico muy grande comparada con las otras variables. Escala dicha variable para que tenga un valor entre 0 y 1.

In [10]:
scaler = MinMaxScaler()
EmpleadosAttrition['MonthlyIncome'] = scaler.fit_transform(EmpleadosAttrition[['MonthlyIncome']])
EmpleadosAttrition['MonthlyIncome']

0      0.864269
1      0.207340
2      0.088062
3      0.497574
4      0.664470
         ...   
395    0.075248
396    0.187197
397    0.589327
398    0.121124
399    0.092122
Name: MonthlyIncome, Length: 400, dtype: float64

9.	Todo parece indicar que las variables categóricas que quedan sí son importantes para obtener la variable de salida. Convierte todas las variables categóricas que quedan a numéricas:
a.	BusinessTravel
b.	Department
c.	EducationField
d.	Gender
e.	JobRole
f.	MaritalStatus
g.	Attrition


In [11]:
EmpleadosAttrition = pd.get_dummies(EmpleadosAttrition, columns=['BusinessTravel', 'Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus'], dtype= np.int64)




10.	Ahora debes hacer la evaluación de las variables para quedarte con las mejores. Calcula la correlación lineal de cada una de las variables con respecto al Attrition.

In [12]:
label_encoder = LabelEncoder()
EmpleadosAttrition['Attrition'] = label_encoder.fit_transform(EmpleadosAttrition['Attrition'])


In [13]:
label_encoder = LabelEncoder()
EmpleadosAttrition['OverTime'] = label_encoder.fit_transform(EmpleadosAttrition['OverTime'])


In [14]:
Correlacion =EmpleadosAttrition.corr()
CorrelacionAttrition = Correlacion['Attrition']
CorrelacionAttrition

Age                                 -0.212121
Education                           -0.055531
EnvironmentSatisfaction             -0.124327
JobInvolvement                      -0.166785
JobLevel                            -0.214266
JobSatisfaction                     -0.164957
MonthlyIncome                       -0.194936
NumCompaniesWorked                  -0.009082
OverTime                             0.324777
PercentSalaryHike                   -0.060880
PerformanceRating                   -0.006471
RelationshipSatisfaction            -0.030945
TotalWorkingYears                   -0.213329
TrainingTimesLastYear               -0.070884
WorkLifeBalance                     -0.021723
YearsInCurrentRole                  -0.203918
YearsSinceLastPromotion             -0.069000
Attrition                            1.000000
YearsAtCompany                      -0.176287
DistanceFromHome                     0.052732
BusinessTravel_Non-Travel           -0.100698
BusinessTravel_Travel_Frequently     0.035387
BusinessTravel_Travel_Rarely         0.042755
Department_Human Resources           0.023389
Department_Research & Development   -0.072269
Department_Sales                     0.066116
EducationField_Human Resources       0.043404
EducationField_Life Sciences        -0.027457
EducationField_Marketing             0.016768
EducationField_Medical              -0.054144
EducationField_Other                -0.004275
EducationField_Technical Degree      0.129104
Gender_Female                        0.028839
Gender_Male                         -0.028839
JobRole_Healthcare Representative   -0.103274
JobRole_Human Resources              0.032714
JobRole_Laboratory Technician        0.125264
JobRole_Manager                     -0.089885
JobRole_Manufacturing Director      -0.042404
JobRole_Research Director           -0.116263
JobRole_Research Scientist           0.007977
JobRole_Sales Executive             -0.003115
JobRole_Sales Representative         0.191294
MaritalStatus_Divorced              -0.107869
MaritalStatus_Married               -0.094734
MaritalStatus_Single                 0.205849
Name: Attrition, dtype: float64

11.	Selecciona solo aquellas variables que tengan una correlación mayor o igual a 0.1, dejándolas en otro frame llamado EmpleadosAttritionFinal. No olvides mantener la variable de salida Attrition; esto es equivalente a borrar las que no cumplen con el límite.

In [18]:
VariableEmpleadosAttritionfinal = CorrelacionAttrition[CorrelacionAttrition >= 0.1]
VariableEmpleadosAttritionfinal


OverTime                           0.324777
Attrition                          1.000000
EducationField_Technical Degree    0.129104
JobRole_Laboratory Technician      0.125264
JobRole_Sales Representative       0.191294
MaritalStatus_Single               0.205849
Name: Attrition, dtype: float64

In [31]:
EmpleadosAttritionFinal = EmpleadosAttrition[
    ['OverTime', 'Attrition', 'EducationField_Technical Degree',
     'JobRole_Laboratory Technician', 'JobRole_Sales Representative',
     'MaritalStatus_Single']
]

12.	Crea una nueva variable llamada EmpleadosAttritionPCA formada por los componentes principales del frame EmpleadosAttritionFinal. Recuerda que el resultado del proceso PCA es un numpy array, por lo que, para hacer referencia a una columna, por ejemplo, la 0, puedes usar la instrucción EmpleadosAttritionPCA[:,0]).

In [41]:
pca= PCA(5)
pca.fit(EmpleadosAttritionFinal)
EmpleadosAttritionPCA=pca.components_

In [36]:
EmpleadosAttritionPCA

array([[ 0.65102913,  0.51633709,  0.03506617, -0.00133043,  0.08615571,
         0.54854614],
       [-0.59143418, -0.09940939, -0.04947109, -0.12562338,  0.11467139,
         0.78034943],
       [-0.23857413,  0.30041027, -0.02294642,  0.92231757, -0.03918037,
         0.01023265],
       [-0.38465022,  0.71570754,  0.22703725, -0.30963329,  0.33356149,
        -0.28482445],
       [ 0.1307161 , -0.34523529,  0.61131546,  0.18978866,  0.67331386,
         0.02545633]])

13.	Agrega el mínimo número de Componentes Principales en columnas del frame EmpleadosAttritionPCA que logren explicar el 80% de la varianza, al frame EmpleadosAttritionFinal. Puedes usar la instrucción assign, columna por columna, llamando a cada una C0, C1, etc., hasta las que vayas a agregar

In [37]:
print(pca.explained_variance_)

[0.24558342 0.19472927 0.14715993 0.09969435 0.05276884]


In [38]:
print(pca.explained_variance_ratio_)
varianza_acumulada = pca.explained_variance_ratio_.cumsum()
num_componentes = (varianza_acumulada >= 0.8).argmax() + 1
print(f"Se necesitan {num_componentes} componentes principales para explicar al menos el 80% de la varianza.")


[0.3123714  0.24768714 0.18718102 0.12680686 0.06711966]
Se necesitan 4 componentes principales para explicar al menos el 80% de la varianza.


In [49]:
EmpleadosAttritionFinal = EmpleadosAttritionFinal.assign(
    C0=EmpleadosAttritionFinal['OverTime'],
    C1=EmpleadosAttritionFinal['EducationField_Technical Degree'],
    C2=EmpleadosAttritionFinal['JobRole_Laboratory Technician'],
    C3=EmpleadosAttritionFinal['JobRole_Sales Representative']
)
EmpleadosAttritionFinal


OverTime  Attrition  EducationField_Technical Degree  \
0           0          0                                0   
1           0          0                                0   
2           0          1                                0   
3           0          0                                0   
4           1          1                                0   
..        ...        ...                              ...   
395         1          1                                0   
396         1          1                                0   
397         1          0                                0   
398         0          0                                0   
399         0          0                                0   

     JobRole_Laboratory Technician  JobRole_Sales Representative  \
0                                0                             0   
1                                0                             0   
2                                0                             1   
3                                0                             0   
4                                0                             0   
..                             ...                           ...   
395                              1                             0   
396                              0                             0   
397                              0                             0   
398                              1                             0   
399                              0                             0   

     MaritalStatus_Single  C0  C1  C2  C3  
0                       0   0   0   0   0  
1                       0   0   0   0   0  
2                       1   0   0   0   1  
3                       1   0   0   0   0  
4                       0   1   0   0   0  
..                    ...  ..  ..  ..  ..  
395                     0   1   0   1   0  
396                     0   1   0   0   0  
397                     0   1   0   0   0  
398                     0   0   0   1   0  
399                     0   0   0   0   0  

[400 rows x 10 columns]

14.	Guarda el set de datos que has formado y que tienes en EmpleadosAttritionFinal en un archivo CSV llamado EmpleadosAttritionFinal.csv. Las últimas columnas que colocaste quedarán después de la variable Attrition, lo cual no importa, pero si gustas lo puedes arreglar antes de escribir el archivo.

In [52]:
EmpleadosAttritionFinal.to_csv('EmpleadosAttritionFinal.csv', index=False)
from google.colab import files
files.download('EmpleadosAttritionFinal.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Fin